# Copyright (C) 2020 by the Georgia Tech Research Institute (GTRI)
# This software may be modified and distributed under the terms of
# the BSD 3-Clause license. See the LICENSE file for details.

defmodule YarnlockTest do
  use ExUnit.Case

  test "extracts dependencies from yarn.lock" do
    {:ok, {lib_map, deps_count}} = Npm.Yarnlockfile.parse!(File.read!("./test/fixtures/yarnlock"))

    parsed_yarn = [{"assert-plus", "1.0.0"}]

    assert deps_count == 1
    assert parsed_yarn == lib_map
  end

  test "returns correct file_names" do
    assert Npm.Yarnlockfile.file_names() == ["yarn.lock"]
  end

  test "keeps higher version when duplicate packages exist" do
    # When the first occurrence has a higher version, the else branch keeps acc unchanged
    content = """
    # yarn lockfile v1

    lodash@^4.17.21:
      version "4.17.21"
      resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

    lodash@^4.17.0:
      version "4.17.0"
      resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.0.tgz"
    """

    {:ok, {lib_map, deps_count}} = Npm.Yarnlockfile.parse!(content)
    assert deps_count == 1
    # Should keep the higher version (4.17.21)
    assert {"lodash", "4.17.21"} in lib_map
  end

  test "a scoped package keeps its scope in the name" do
    # Splitting the key at the first "@" left scoped packages with an empty name.
    content = """
    # yarn lockfile v1

    "@babel/core@^7.0.0", "@babel/core@^7.1.0":
      version "7.24.0"
      resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.0.tgz"
    """

    assert {:ok, {[{"@babel/core", "7.24.0"}], 1}} = Npm.Yarnlockfile.parse!(content)
  end

  test "duplicate versions compare as versions, not floats" do
    # Float.parse("1.10.0") is 1.1, which sorted below 1.9.
    for {first, second} <- [{"1.9.0", "1.10.0"}, {"1.10.0", "1.9.0"}] do
      content = """
      # yarn lockfile v1

      minimist@^1.0.0:
        version "#{first}"

      minimist@^1.2.0:
        version "#{second}"
      """

      assert {:ok, {[{"minimist", "1.10.0"}], 1}} = Npm.Yarnlockfile.parse!(content)
    end
  end

  test "a version that is not semver still parses" do
    content = """
    # yarn lockfile v1

    odd@^1:
      version "1.0"

    odd@^1.0.1:
      version "1.0.1"
    """

    assert {:ok, {[{"odd", "1.0.1"}], 1}} = Npm.Yarnlockfile.parse!(content)
  end

  test "extracts dependencies from a yarn 2+ (berry) lockfile" do
    content = """
    # This file is generated by running "yarn install" inside your project.
    # Manual changes might be lost - proceed with caution!

    __metadata:
      version: 8
      cacheKey: 10c0

    "@babel/core@npm:^7.0.0":
      version: 7.24.0
      resolution: "@babel/core@npm:7.24.0"
      languageName: node
      linkType: hard

    "lodash@npm:^4.17.0, lodash@npm:^4.17.21":
      version: 4.17.21
      resolution: "lodash@npm:4.17.21"
      languageName: node
      linkType: hard

    "my-app@workspace:.":
      version: 0.0.0-use.local
      resolution: "my-app@workspace:."
      languageName: unknown
      linkType: soft
    """

    assert {:ok, {deps, 2}} = Npm.Yarnlockfile.parse!(content)
    assert Enum.sort(deps) == [{"@babel/core", "7.24.0"}, {"lodash", "4.17.21"}]
  end
end
