# Copyright (C) 2020 by the Georgia Tech Research Institute (GTRI)
# This software may be modified and distributed under the terms of
# the BSD 3-Clause license. See the LICENSE file for details.

defmodule CargolockTest do
  use ExUnit.Case

  test "extracts packages from Cargo.lock" do
    {:ok, {packages, count}} =
      Cargo.Cargolock.parse!(File.read!("./test/fixtures/cargolock"))

    assert count == 5

    serde = Keyword.get(packages, :serde)
    assert serde.name == "serde"
    assert serde.version == "1.0.188"
    assert serde.source_url == {:crates_io, nil}
  end

  test "returns correct file_names" do
    assert Cargo.Cargolock.file_names() == ["Cargo.lock"]
  end

  test "parses git sources with branch and commit" do
    {:ok, {packages, _count}} =
      Cargo.Cargolock.parse!(File.read!("./test/fixtures/cargolock"))

    custom_lib = Keyword.get(packages, :"custom-lib")
    assert custom_lib.version == "0.5.0"
    assert {:git, %{url: url, commit: commit}} = custom_lib.source_url
    assert url == "https://github.com/example/custom-lib"
    assert commit == "abc123def456"
  end

  test "parses git sources from other hosts" do
    {:ok, {packages, _count}} =
      Cargo.Cargolock.parse!(File.read!("./test/fixtures/cargolock"))

    private_dep = Keyword.get(packages, :"private-dep")
    assert {:git, %{url: url, commit: _}} = private_dep.source_url
    assert url == "https://gitlab.example.com/team/private-dep"
  end

  test "handles packages without source (local path dependencies)" do
    {:ok, {packages, _count}} =
      Cargo.Cargolock.parse!(File.read!("./test/fixtures/cargolock"))

    local = Keyword.get(packages, :"local-crate")
    assert local.name == "local-crate"
    assert local.version == "0.1.0"
    assert local.source == nil
    assert local.source_url == nil
  end

  test "handles empty Cargo.lock" do
    content = """
    # This file is automatically @generated by Cargo.
    version = 3
    """

    {:ok, {packages, count}} = Cargo.Cargolock.parse!(content)
    assert count == 0
    assert packages == []
  end

  test "handles Cargo.lock with only crates.io dependencies" do
    content = """
    [[package]]
    name = "rand"
    version = "0.8.5"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    """

    {:ok, {packages, count}} = Cargo.Cargolock.parse!(content)
    assert count == 1

    rand = Keyword.get(packages, :rand)
    assert rand.version == "0.8.5"
    assert rand.source_url == {:crates_io, nil}
  end
end
